<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateVDataHeaderTable extends Migration
{

    protected $connection = 'sqlsrv2';
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $this->down();
        Schema::connection('sqlsrv2')->create('v_data_header', function (Blueprint $table) {
            $table->increments('id_ppk');
            $table->string('no_ppk');   
            $table->string('no_aju_ppk');
            $table->integer('id_trader')->unsigned();
            $table->string('nm_trader');
            $table->string('al_trader');
            $table->date('tgl_ppk');
            $table->string('kd_kegiatan'); //raha=E afif=K
            $table->string('nm_penerima');
            $table->string('alamat');
            $table->string('Negara_penerima');
            /*
            no_ssm
            karantina_mutu
            kd_input
            tgl_input
            tgl_berangkat
            id_trader
            id_penerima
            id_instalasi
            id_ppjk
            id_kontak
            id_angkut
            no_moda
            nm_moda
            jns_sarana
            jns_sarana_en
            flag_moda
            id_angkut_transit
            no_moda_transit
            flag_moda_transit
            kd_mks_kirim
            sts_syarat
            id_komoditas
            kid12
            kid14
            kd_upt_tujuan
            negara_propinsi
            jns_tangkapan
            konsumsi
            bruto
            netto
            nilai
            usd
            id_stn
            sts_dok
            sts_jju
            sts_lain
            sts_klinis
            sts_lab
            sts_ppk
            sts_up
            fx_trader
            nm_trader
            al_trader
            ph_trader
            kdpos_trader
            email
            email_pjb
            nm_penerima
            alamat
            kdpos_pnrm
            telp_pnrm
            email_pnrm
            maksud_pengiriman
            keterangan
            ket_jenis
            nm_kegiatan
            nm_negara
            Negara_penerima
            tgl_periksa
            tgl_periksa_2
            kd_pel_muat	
            kd_pel_transit
            kd_pel_bongkar
            voyage
            voyage_transit
            id_timbun
            no_tugas
            id_p123
            tgl_tugas
            nip_baru
            add_info
            satuan_nil
            nm_trans
            trans_transit
            moda_transit
            propinsi_trader
            prop_trd_nsw
            id_skib
            no_skib
            tgl_skib
            tgl_berlaku_skib
            id_s
            no_s
            tgl_s
            kd_tempat
            sts_print
            sts_data
            p8
            sampel
            nm_instalasi
            al_instalasi
            p15
            pembatalan
            p7	p6	p5
            kode
            uraian
            ngr_prop_penerima
            npwp
            no_ktp
            nm_unit
            nm_kpbc
            kota_kpbc
            nm_ppjk
            al_ppjk
            npwp_ppjk
            nm_kontak
            al_kontak
            telp
            nm_tempat
            kpbc
            sp3zk
            p11	p12	p13	p14	p2	p3	p4
            kawal
            ngr_transit
            area_transit
            id_sub_kategori
            id_kel_mp
            id_bentuk
            id_sts_mp
            id_mutu
            id_upi
            no_reg
            kd_ngr_reg
            nm_upi
            al_upi
            telp_upi
            kodepos_upi
            no_surveilance
            tgl_surveilance
            kd_tgl_produksi
            mode_produksi
            deskripsi_produk
            kd_jns_produk
            kapal_pengolah
            jns_air
            kapal_tangkap_olah
            kapal_transport
            kd_wil_asal_produk
            cultured
            cultured_area
            wild
            catch_area
            uraian_temperature
            temperature
            jenis_temperature
            gudang_coldstorage
            hscode_mutu
            ngr_asal_produk
            kd_ngr_asal_produk
            no_reg_ue
            nilai_komoditas_usd
            code_qr
            ket_sub_kategori
            jenis_produk_mutu
            id_ijin_header
            no_ijin
            tgl_terbit
            tgl_berlaku
            finfish
            mollusca
            crustasea
            fishery
            shrimp
            oyster
            abalone
            others
            atts_note
            id_hasil_analisa_mp
            jns_upi
            ucp_whs
            kt_port
            kota_trd_nsw*/
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::connection('sqlsrv2')->dropIfExists('v_data_header');
    }
}
